# https://hub.docker.com/r/library/node/tags/
image: node:latest
# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
#AWS access keys stored as secret variables 

#This declares the pipeline stages  
stages:
  - build
#   - test
  - deploy
cache:
  paths:
  - node_modules/
build:
  stage: build
  artifacts:
        paths:
        - build/
  script:
    - npm install
    - CI=false npm run-script build
# test:
#   stage: test
#   script:
#     - echo "Running react test suite......"
deploy:
  image: python:latest
  stage: deploy
#   script:
#     - npm run-script deploy
  script:
    - pip install awscli
    - aws s3 cp ./build/ s3://ecom-website/ --recursive --exclude ".*"